version: 2.0

jobs:
  "node-8":
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/node8
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Run tests
          command: node ./dist/src/cli.js

  "node-9":
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/node9
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Run tests
          command: node ./dist/src/cli.js

  "node-10":
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/node10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Run tests
          command: node ./dist/src/cli.js

workflows:
  version: 2
  build:
    jobs:
      - "node-8"
      - "node-9"
      - "node-10"